# Generated by Django 5.1.4 on 2025-01-24 19:34

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن')),
                ('car_number', models.CharField(max_length=16, unique=True, verbose_name='شماره ماشین')),
                ('car_type', models.CharField(choices=[('pickup', 'وانت'), ('truck', 'کامیون')], max_length=16, verbose_name='نوع ماشین')),
                ('capacity', models.IntegerField(default=10000, verbose_name='حجم ماشین (لیتر)')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'راننده',
                'verbose_name_plural': 'رانندگان',
            },
        ),
    ]
