# Generated by Django 5.1.4 on 2025-01-24 19:34

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('code_melli', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('notebook_number', models.CharField(max_length=32, unique=True, verbose_name='شماره دفترچه')),
                ('address', models.CharField(default='', max_length=500, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'مالک',
                'verbose_name_plural': 'مالک ها',
            },
        ),
        migrations.CreateModel(
            name='FarmlandType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نوع مزرعه',
                'verbose_name_plural': 'نوع های مزرعه',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'منطقه',
                'verbose_name_plural': 'مناطق',
            },
        ),
        migrations.CreateModel(
            name='Farmland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='مساحت (هکتار)')),
                ('tree_count', models.IntegerField(default=0, verbose_name='تعداد درخت')),
                ('address', models.CharField(default='', max_length=500, verbose_name='آدرس')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmland.farmer', verbose_name='مالک')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmland.farmlandtype', verbose_name='نوع')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmland.zone', verbose_name='منطقه')),
            ],
            options={
                'verbose_name': 'مزرعه',
                'verbose_name_plural': 'مزرعه ها',
            },
        ),
    ]
