# Generated by Django 5.1.4 on 2025-07-07 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_payment_content_type_payment_object_id'),
        ('order', '0007_orderreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='order.waterorder', verbose_name='حواله'),
        ),
    ]
