# Generated by Django 5.1.4 on 2025-01-24 19:34

import django.db.models.deletion
import django_jalali.db.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        ('farmland', '0001_initial'),
        ('water_source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('fa_name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('template', tinymce.models.HTMLField(default='', verbose_name='قالب')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'توضیحات حواله',
                'verbose_name_plural': 'توضیحات حواله',
            },
        ),
        migrations.CreateModel(
            name='WaterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_source_type', models.CharField(choices=[('liter', 'لیتر'), ('time', 'ساعت')], max_length=16, verbose_name='واحد مقدار آب')),
                ('amount', models.IntegerField(default=0, verbose_name='مقدار آب')),
                ('pump_count', models.IntegerField(default=0, verbose_name='پمپاژ محدد')),
                ('pipe_length_price_type', models.CharField(choices=[('free', 'رایگان'), ('fix', 'ثابت'), ('dynamic', 'متغیر')], default='fix', max_length=16, verbose_name='نوع هزینه لوله')),
                ('pipe_length', models.IntegerField(default=0, verbose_name='طول لوله (کیلومتر)')),
                ('valid_date', django_jalali.db.models.jDateField(verbose_name='تاریخ اعتبار')),
                ('water_price_base', models.IntegerField(default=0, verbose_name='قیمت پایه آب')),
                ('pipe_price_base', models.IntegerField(default=0, verbose_name='قیمت پایه لوله')),
                ('pump_price_base', models.IntegerField(default=0, verbose_name='قیمت پایه پمپاژ')),
                ('total_price', models.IntegerField(default=0, verbose_name='مبلغ کل')),
                ('created_date_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_time_at', models.TimeField(auto_now_add=True, verbose_name='ساعت ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver', verbose_name='راننده')),
                ('farmland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmland.farmland', verbose_name='مزرعه')),
                ('water_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_source.watersource', verbose_name='منبع آب')),
            ],
            options={
                'verbose_name': 'حواله آب',
                'verbose_name_plural': 'حواله های آب',
            },
        ),
    ]
