# Generated by Django 5.1.4 on 2025-02-05 07:31

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(default=0)),
                ('reset_date', django_jalali.db.models.jDateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='waterorder',
            name='number',
            field=models.BigIntegerField(default=0),
        ),
    ]
