# Generated by Django 5.1.4 on 2025-02-07 10:06

import django.db.models.deletion
import django_jalali.db.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmland', '0001_initial'),
        ('order', '0002_ordernumber_waterorder_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='کد کالا')),
                ('unit', models.IntegerField(choices=[('number', 'عدد'), ('kilogram', 'کیلوگرم')], verbose_name='واحد')),
                ('price', models.BigIntegerField()),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نهاده',
                'verbose_name_plural': 'نهاده ها',
            },
        ),
        migrations.AlterField(
            model_name='waterorder',
            name='number',
            field=models.BigIntegerField(default=0, verbose_name='شماره'),
        ),
        migrations.CreateModel(
            name='GoodsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(default=0, verbose_name='شماره')),
                ('description', tinymce.models.HTMLField(verbose_name='توضیحات')),
                ('discount_type', models.CharField(choices=[('fix', 'ثابت'), ('percent', 'درصد')], default='fix', max_length=8, verbose_name='نوع تخفیف')),
                ('discount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='میزان تخفیف')),
                ('tax', models.BooleanField(default=False, verbose_name='مالیات')),
                ('created_date_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_time_at', models.TimeField(auto_now_add=True, verbose_name='ساعت ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmland.farmer', verbose_name='کشاورز')),
            ],
            options={
                'verbose_name': 'حواله نهاده',
                'verbose_name_plural': 'حواله های نهاده',
            },
        ),
        migrations.CreateModel(
            name='GoodsOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.BigIntegerField(default=0)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('discount_type', models.CharField(choices=[('fix', 'ثابت'), ('percent', 'درصد')], default='fix', max_length=8, verbose_name='نوع تخفیف')),
                ('discount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='میزان تخفیف')),
                ('goods_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_order_goods_order_item', to='order.goodsorder', verbose_name='حواله کالا')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_goods_order_item', to='order.goodsitem', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'اقلام حواله نهاده',
                'verbose_name_plural': 'اقلام حواله های نهاده',
            },
        ),
    ]
