# Generated by Django 5.1.4 on 2025-02-07 10:12

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_goodsitem_alter_waterorder_number_goodsorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsitem',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='price',
            field=models.BigIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='unit',
            field=models.CharField(choices=[('number', 'عدد'), ('kilogram', 'کیلوگرم')], max_length=16, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان به روز رسانی'),
        ),
    ]
