# Generated by Django 5.1.4 on 2025-02-07 13:03

import django_jalali.db.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_goodsitem_created_at_alter_goodsitem_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsorderitem',
            options={'verbose_name': 'قلم حواله نهاده', 'verbose_name_plural': 'اقلام حواله های نهاده'},
        ),
        migrations.AlterField(
            model_name='goodsorder',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='goodsorderitem',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='goodsorderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='goodsorderitem',
            name='unit_price',
            field=models.BigIntegerField(default=0, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='goodsorderitem',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان به روز رسانی'),
        ),
    ]
