# Generated by Django 5.1.4 on 2025-02-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_goodsorderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsorder',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='مبلغ نهایی'),
        ),
    ]
