# Generated by Django 5.1.4 on 2025-07-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_goodsorder_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReport',
            fields=[
            ],
            options={
                'verbose_name': 'گزارش حواله',
                'verbose_name_plural': 'گزارش حواله\u200cها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.waterorder',),
        ),
    ]
