# Generated by Django 5.1.4 on 2025-12-14 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('order', '0007_orderreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterorder',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver', verbose_name='راننده'),
        ),
    ]
